version: '3.7'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./config/db/my.cnf:/etc/mysql/conf.d/my2.cnf
    env_file:
      - ./.envs/.local/.rust
    ports:
      - "23308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: .
      dockerfile: ./containers/api/Dockerfile
      target: "development-stage"
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    env_file:
      - ./.envs/.local/.rust
    command: /local
    tty: true
  reverse-proxy:
    image:  nginx:1.19
    depends_on:
      - api
    volumes:
      - ./config/reverse-proxy/user.conf:/etc/nginx/conf.d/default.conf
      - proxysocket:/tmp/tmp
    ports:
      - "8000:8000"
volumes:
  proxysocket: # ソケットのための共通ボリューム
  cargo-cache:
  target-cache:
