-- MySQL Script generated by MySQL Workbench
-- Sun Dec  5 12:00:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `our-chat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `our-chat`.`users` (
  `id` BINARY(16) NOT NULL DEFAULT (RANDOM_BYTES(16)),
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `our-chat`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `our-chat`.`rooms` (
  `id` BINARY(16) NOT NULL DEFAULT (RANDOM_BYTES(16)),
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `our-chat`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `our-chat`.`messages` (
  `id` BINARY(16) NOT NULL DEFAULT (RANDOM_BYTES(16)),
  `user_id` BINARY(16) NOT NULL,
  `room_id` BINARY(16) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `send_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_room_id_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `our-chat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `our-chat`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `our-chat`.`subscribes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `our-chat`.`subscribes` (
  `id` BINARY(16) NOT NULL DEFAULT (RANDOM_BYTES(16)),
  `user_id` BINARY(16) NOT NULL,
  `room_id` BINARY(16) NOT NULL,
  `subscribe_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_subscribe_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_subscribe_room1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscribe_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `our-chat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscribe_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `our-chat`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
