version: 0.2

phases:
  install:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - echo Logging in to Docker Hub...
      - echo At%d]2w3zDG+q]B | docker login -u mamatching --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - pwd
      - docker build -f containers/nginx/Dockerfile -t web-backend-nginx .
      - docker images
      - docker tag web-backend-nginx:latest 594955594561.dkr.ecr.ap-northeast-1.amazonaws.com/prod-web-backend-nginx:latest

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 594955594561.dkr.ecr.ap-northeast-1.amazonaws.com/prod-web-backend-nginx:latest
